Fix crashes (#139)
* fix: annotate SideOnly property 1

* fix: possible NPE in getDrops

* fix: convert prop to method

* fix: client only LaserReflectorItemStackRenderer

* fix: don't override getItemStackDisplayName

* fix: server crash

* fix: remove @SideOnly from rangeRenderMode

* fix: NoClassDefFoundError WhenMappings

* fix: I18n call on the server

* fix: use columnWithPlayerInv instead of mainColumn